### ISSUE TITLE
Create database model for CarShop

### ISSUE THREAD

**Issue by JoeDLehmanJr** [JoeDLehmanJr/Summer2022-CPW211-TeamProject#1]
Create data base mode for the CarShop database

**Comment by jwestphalen** [comment]
test message

**Comment by JoeDLehmanJr** [comment]
Collaborated on the initial design of our database. See Visio drawing at https://github.com/JoeDLehmanJr/Summer2022-CPW211-TeamProject/blob/main/Car%20Shop.vsdx
